#!/bin/bash

python src/documentClassifier.py random ../twitterProcessed.data 1 1 > output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 2 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 3 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 4 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 5 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 6 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 7 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 8 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 9 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 10 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 11 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 12 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 13 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 14 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 15 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 16 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 17 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 18 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 19 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 20 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 21 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 22 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 23 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 24 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 25 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 26 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 27 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 28 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 29 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 30 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 31 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 32 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 33 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 34 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 35 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 36 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 37 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 38 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 39 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 40 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 41 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 42 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 43 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 44 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 45 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 46 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 47 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 48 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 49 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 50 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 51 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 52 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 53 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 54 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 55 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 56 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 57 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 58 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 59 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 60 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 61 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 62 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 63 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 64 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 65 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 66 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 67 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 68 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 69 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 70 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 71 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 72 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 73 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 74 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 75 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 76 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 77 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 78 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 79 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 80 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 81 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 82 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 83 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 84 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 85 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 86 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 87 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 88 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 89 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 90 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 91 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 92 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 93 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 94 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 95 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 96 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 97 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 98 >> output/twitter/validationF-1_1-99.txt
python src/documentClassifier.py random ../twitterProcessed.data 1 99 >> output/twitter/validationF-1_1-99.txt