#!/bin/bash

python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 1 > output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 2 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 3 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 4 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 5 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 6 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 7 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 8 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 9 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 10 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 11 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 12 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 13 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 14 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 15 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 16 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 17 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 18 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 19 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 20 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 21 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 22 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 23 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 24 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 25 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 26 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 27 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 28 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 29 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 30 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 31 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 32 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 33 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 34 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 35 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 36 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 37 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 38 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 39 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 40 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 41 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 42 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 43 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 44 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 45 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 46 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 47 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 48 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 49 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 50 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 51 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 52 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 53 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 54 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 55 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 56 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 57 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 58 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 59 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 60 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 61 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 62 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 63 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 64 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 65 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 66 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 67 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 68 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 69 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 70 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 71 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 72 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 73 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 74 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 75 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 76 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 77 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 78 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 79 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 80 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 81 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 82 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 83 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 84 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 85 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 86 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 87 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 88 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 89 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 90 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 91 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 92 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 93 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 94 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 95 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 96 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 97 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 98 >> output/twitter/validation-10_1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData2.txt 10 99 >> output/twitter/validation-10_1-99.txt