#!/bin/bash

python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 1 > output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 2 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 3 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 4 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 5 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 6 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 7 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 8 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 9 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 10 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 11 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 12 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 13 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 14 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 15 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 16 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 17 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 18 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 19 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 20 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 21 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 22 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 23 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 24 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 25 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 26 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 27 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 28 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 29 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 30 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 31 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 32 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 33 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 34 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 35 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 36 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 37 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 38 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 39 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 40 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 41 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 42 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 43 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 44 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 45 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 46 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 47 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 48 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 49 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 50 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 51 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 52 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 53 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 54 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 55 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 56 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 57 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 58 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 59 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 60 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 61 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 62 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 63 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 64 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 65 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 66 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 67 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 68 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 69 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 70 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 71 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 72 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 73 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 74 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 75 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 76 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 77 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 78 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 79 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 80 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 81 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 82 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 83 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 84 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 85 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 86 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 87 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 88 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 89 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 90 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 91 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 92 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 93 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 94 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 95 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 96 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 97 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 98 >> output/twitter/validation_2-1-99.txt
python src/documentClassifier.py random data/twitterdata/sampleTwitterData.txt 1 99 >> output/twitter/validation_2-1-99.txt